### ISSUE TITLE
Comment input box is shown twice

### ISSUE THREAD

**Issue by flip111** [timber/starter-theme#101]
One include

https://github.com/timber/starter-theme/blob/cc8e530a9cd5ece12467dd1a95e1bf47e4b618a8/templates/single.twig#L34

Above that `comments.twig` is included

https://github.com/timber/starter-theme/blob/cc8e530a9cd5ece12467dd1a95e1bf47e4b618a8/templates/single.twig#L25

Which renders another comment box

https://github.com/timber/starter-theme/blob/41c74ff9d68ff36fce4e1561e9cd98ddda1c6286/templates/comment.twig#L8

**Comment by flip111** [comment]
Maybe i did not understood this correctly. And comments itself can be commented to. Though i don't see variables passed down to the form so how to distinguish .. i think it's still an incomplete example. Better leave out things if they don't fully work

**Comment by marciojc** [comment]
Each form has a hidden input (comment_parent) with a comment.ID or 0. That way we can distinguer them.

**Comment by flip111** [comment]
Thanks for your explanation
