### ISSUE TITLE
Can't use Timber as parent theme with new folder structure

### ISSUE THREAD

**Issue by Saelya** [timber/starter-theme#104]
We use Timber as a parent theme and when we try to activate our child theme it says that "The parent theme is missing"

**Comment by szepeviktor** [comment]
> Timber as a parent theme

So you use the starter-theme as a parent theme.

AFAIK the starter-theme is for starting working on it. README says: _a dead-simple theme_.
Having a parent theme is for not overwriting the the theme's code but the starter theme won't really have new features.

Despite the above I start investigating what is going on...

**Comment by szepeviktor** [comment]
BTW Welcome to GitHub!

**Comment by szepeviktor** [comment]
Results are coming in :)

```css
/*
 * Theme Name: Another Starter Theme
 * Template: starter-theme/theme
 */
```

Add `/theme` to you child theme's meta header as depicted above.

**Comment by jarednova** [comment]
See #105 for more info on resolution
