### ISSUE TITLE
home.twig template doesn't exist

### ISSUE THREAD

**Issue by misfist** [timber/starter-theme#11]
`index.php` contains the following:

``` php
$templates = array( 'index.twig' );
if ( is_home() ) {
    array_unshift( $templates, 'home.twig' );
}
```

So, if the current page is the home page, `home.twig` should be added in front of `index.twig` in the `$template` array, yet there is no `home.twig` template included.

**Comment by alenabdula** [comment]
@misfist 

`array_unshift()` - prepends passed elements to the front of the array. [php.net](http://php.net/manual/en/function.array-unshift.php)

If there's no `home.twig` template it will default to `index.twig`. Think of the `$templates` array as fallback list of templates. This starter theme is just emulating what WordPress already does if you review [WordPress Template Hierarchy](https://developer.wordpress.org/themes/basics/template-hierarchy).
