### ISSUE TITLE
gravity forms set to display none

### ISSUE THREAD

**Issue by pixelstorm** [timber/starter-theme#114]
my forms have conditional logic on them, which adds a display: none inline tag to the forms. the display: none tag remains on the form as wp-footer() is not loading (i think). How can i ensure wp-footer() function is loaded?

**Comment by jarednova** [comment]
Hi there! Sorry to hear you're having issues (but glad you're giving Timber a try!) We try to keep GitHub clear for just bugs with the Timber code itself. For questions like this, please post to the StackOverflow channel:

http://stackoverflow.com/questions/tagged/timber

If you post a link to your question back on this issue, I'll try to follow-up there if there's an answer I can provide
