### ISSUE TITLE
Advice to install timber.

### ISSUE THREAD

**Issue by flip111** [timber/starter-theme#123]
As i understood development on the 1.* branch has slowed down and the main focus is now on 2.*. Since i'm starting a fresh theme i will go with the 2.* branch. Which advices me to install the plugin with composer directly into the theme. See https://github.com/timber/timber/tree/2.x#installation Which i also like because it gives me a bit more control and i'm not that big of a wordpress fan ironically. For starting the theme i also take the 2.* branch of the starter theme. My question is if i can still use composer to install timber, or should i follow the instructions in the theme https://github.com/timber/timber/tree/2.x#installation to use the wordpress plugin instead?

**Comment by szepeviktor** [comment]
AFAIK Timber v2 contains features not allowed on WP.org.

Please see

https://github.com/timber/starter-theme/blob/2f8e086475964f9846a546aad2000401cd956656/composer.json#L20

which will later be `"timber/timber": "^2.0"`

**Comment by szepeviktor** [comment]
Please consider pressing <kbd>ENTER</kbd> while writing your comment to please readers :)

**Comment by flip111** [comment]
Thank you @szepeviktor .. i conclude from your answer the readme has to be updated with this information and i can go ahead and use composer.
