### ISSUE TITLE
Installing Timber on Local Environment with Composer 2.0 Issues

### ISSUE THREAD

**Issue by adriculous** [timber/starter-theme#126]
Hello,

Recently, I signed up for a course for WordPress theme development with Timber and Twig. I tried to install the Timber plugin via Composer. I had Composer 1 before, but it wouldn't execute the installation because it has been deprecated. So, I had to update it to Composer 2.

After I updated it and tried to run installation again using `composer require timber/timber`, I'm getting this error message:

    Using version ^1.18 for timber/timber
    ./composer.json has been updated
    Running composer update timber/timber
    Loading composer repositories with package information
    Updating dependencies
    Your requirements could not be resolved to an installable set of packages.

    Problem 1
     - phpunit/phpunit 5.7.16 requires php ^5.6 || ^7.0 -> your php version (8.0.8) does not satisfy that requirement.
     - phpunit/phpunit[6.0.0, ..., 6.5.14] require php ^7.0 -> your php version (8.0.8) does not satisfy that requirement.
     - Root composer.json requires phpunit/phpunit 5.7.16|6.* -> satisfiable by phpunit/phpunit[5.7.16, 6.0.0, ..., 6.5.14].

I've looked around for answers but there are a lot of different answers or that a lot of them don't make sense to me. Unfortunately, the course I signed up for have outdated information regarding setup, so if there's anyone who can help me out, I would truly appreciate it. Thank you!

**Comment by szepeviktor** [comment]
You are running PHP 8. Old PHPUnit vesions do not run on PHP 8.
https://phpunit.de/supported-versions.html

**Comment by szepeviktor** [comment]
Timber v1 does not support PHP 8 (yet)
https://github.com/timber/timber/issues/2385

**Comment by adriculous** [comment]
Thank you, I know my issue sounds newbie-ish (as I am a newbie). I went around to installing and switching to 7.4. I installed Timber and it worked perfectly. Thank you again!
