### ISSUE TITLE
Upload to packagist?

### ISSUE THREAD

**Issue by rbvea** [timber/starter-theme#13]
Looks like https://packagist.org/search/?q=timber-starter-theme yields nothing, and I'm having trouble getting it to install with the vcs option in composer.

**Comment by rbvea** [comment]
Actually... looks like it's trying to require `wpackagist-plugin/timber-library 0.21.*` but that's out of date

**Comment by szepeviktor** [comment]
Done!
https://packagist.org/packages/upstatement/timber-starter-theme

**Comment by rbvea** [comment]
Woop, thanks!
