### ISSUE TITLE
Can starter-theme v2 for timber v2 be already tested (via composer)?

### ISSUE THREAD

**Issue by mandrasch** [timber/starter-theme#135]
Hi,

just super curious what the current state of the starter theme is? Would love to check out timber v2 with starter theme v2.

Tried installing via `composer create-project upstatement/timber-starter-theme:2.x-dev --no-dev`, but I got:

```bash
Creating a "upstatement/timber-starter-theme:2.x-dev" project at "./timber-starter-theme"
Installing upstatement/timber-starter-theme (2.x-dev 2540bb62444d7b8066faacbc18cdcc48ea26fe18)
  - Downloading upstatement/timber-starter-theme (2.x-dev 2540bb6)
  - Installing upstatement/timber-starter-theme (2.x-dev 2540bb6): Extracting archive
Created project in /var/www/html/wp-content/themes/timber-starter-theme
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires timber/timber dev-2.x-term-factories, found timber/timber[dev-new_object_factory, ..., dev-pr/2632, 0.16.6, ..., 0.x-dev, v1.0-rc.1, ..., 1.20.0, 2.0.0-alpha.1, ..., 2.x-dev] but it does not match the constraint.
  Problem 2
    - phpunit/phpunit[7.0.0, ..., 7.5.20] require php ^7.1 -> your php version (8.0.21) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit 7.* -> satisfiable by phpunit/phpunit[7.0.0, ..., 7.5.20].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
```

I run DDEV with php_version: "8.0". 

(Also I wondered why the docs suggest --no-dev for dev environments)

Thanks in advance for reply & much success with finishing timber v2! 

Great that this is provided as Open Source!

**Comment by szepeviktor** [comment]
Hello Matthias! 👋🏻 
Thank you for report.

> requires timber/timber dev-2.x-term-factories

Seems like this branch has been deleted over there at Timber.

See 👇🏻

**Comment by mandrasch** [comment]
Thanks very much @szepeviktor for information on Problem 1!  

(btw: My source code is published here https://github.com/mandrasch/ddev-wp-timber-v2 if anyone wants to have a look)

**Comment by szepeviktor** [comment]
You're welcome.

[off] Please consider managing your WordPress installation with Composer: https://github.com/szepeviktor/composer-managed-wordpress
