### ISSUE TITLE
Issue with 2.0 theme after most recent folder restructuring

### ISSUE THREAD

**Issue by dreamersofdreams** [timber/starter-theme#141]
Have been doing a lot of local testing recently with starter theme 2.0.  Was running great until I just tried implementing these recent updates https://github.com/timber/starter-theme/pull/139 

Just a blank screen - no error message. 

Spun up a fresh new local site with Starter theme 2.0 (with those changes from https://github.com/timber/starter-theme/pull/139) and same thing - just blank white screen.  Will try and do some more troubleshooting, but just throwing out there now since this just got implemented yesterday...

**Comment by dreamersofdreams** [comment]
Just a quick follow up:  On my fresh install, I just reverted everything back - moved everything back into a "theme" folder and then reverted the functions.php and test-timber-starter-theme.php file back to how it was before the #139 merge. And everything worked again...  So I'm guessing that perhaps there may still be something trying to point to "theme" directory? 
Have no idea what that  test-timber-starter-theme.php file actually does, however, there is still a reference to the /theme directory... 
switch_theme( basename( dirname( __DIR__ ) ) . '/theme' );
Just a hunch.

**Comment by szepeviktor** [comment]
The problem may be here, this line has not been reverted
https://github.com/timber/starter-theme/blob/1254c2fbec8728c4c2722a8bb0e73ef19ca0d932/functions.php#L47

was
https://github.com/timber/starter-theme/blob/cc8e530a9cd5ece12467dd1a95e1bf47e4b618a8/functions.php#L47

**Comment by dreamersofdreams** [comment]
@szepeviktor Yep that was it - thanks for catching! So that'll need to be updated in main 2.0 branch.

**Comment by gchtr** [comment]
Thanks for reporting this and for the solution. I may have merged that pull request too early. I tried to fix the automated test after that, but couldn’t finish before the weekend.

We’ll bring the tests back in https://github.com/timber/starter-theme/pull/142 together with a fix for this.

**Comment by Levdbas** [comment]
Should be fixed, closing
