### ISSUE TITLE
Publish starter theme again to the Timber packagist

### ISSUE THREAD

**Issue by Levdbas** [timber/starter-theme#161]
> Yes, it makes sense :). I just wanted to make sure we keep track of this todo.

_Originally posted by @gchtr in https://github.com/timber/starter-theme/pull/154#discussion_r1599536534_

**Comment by szepeviktor** [comment]
@Levdbas Blockquote in Markdown is `> `

**Comment by Levdbas** [comment]
@jarednova , could you deprecate https://packagist.org/packages/upstatement/timber-starter-theme in favor of https://packagist.org/packages/timber/starter-theme?

**Comment by szepeviktor** [comment]
[off topic] @jarednova What about you? The Jared-Timber distance just got bigger?

**Comment by jarednova** [comment]
@Levdbas happy to! 

@szepeviktor that's the idea — want to make sure Timber can thrive without old Jared-y ways of doing things

**Comment by Levdbas** [comment]
Thanks Jared!

**Comment by jarednova** [comment]
No, thank YOU @Levdbas !
