### ISSUE TITLE
comment_form() echoes the comment form...

### ISSUE THREAD

**Issue by PauGNU** [timber/starter-theme#21]
The change done in commit: https://github.com/timber/starter-theme/commit/04aa1dad0d4dfa3553fab719b454063c64ca4bda

Changes the deprecated function from Timber to the one native from wordpress. However, the behavior of the wordpress function is different: it echoes the comment form instead of just passing the comment form result to the variable. As a consequence, the comment form appears on the top of any page where it is called.

**Comment by connorjburton** [comment]
Very true, my bad. What we will actually have to do is call `comment_form` in the template. I will update the repo now.

**Comment by connorjburton** [comment]
Merged
