### ISSUE TITLE
Any plan to update to the latest version of Underscores

### ISSUE THREAD

**Issue by utsavdevsharma** [timber/starter-theme#25]
Hey guys @connorjburton @jarednova 

First of all thanks a lot for creating Timber and this starter theme. 

I just wanted to know, is there any plan to **update** this starter theme to the latest version of underscores? I am afraid the base html and the functions in this starter theme have got way too old 😭 

Please let me know guys, Thanks in advance!

**Comment by Daronspence** [comment]
Which functions do you think are out of date @utsavdevsharma? I think I could find some time this weekend to open a PR updating some of that if it makes sense. A lot of template tags aren't needed though since you should be adding most of that data to your Timber context :)

**Comment by connorjburton** [comment]
PR's are very welcome if this is necessary for anyone. I will add an issue to change to namespaces too.

**Comment by NazimHAli** [comment]
Underscores is deprecated and will be archived, no longer updated. Has anyone used https://blockbasetheme.com/ at https://github.com/Automattic/themes/tree/trunk/blockbase from Automattic? Because of the major changes in WordPress, we have to consider the 2 approaches now. I've been struggling with trying to figure this out myself, so did some research and the reasons for this are compelling:

> WordPress is still in a transition phase – block themes are in a nascent stage and don’t offer the full gamut of features that will be available in the future. This puts theme developers in a bind; do we:
> 
> - Continue building classic themes and ignore the Full Site Editor.
>     - This is easier in the short term, but it ties our users in to the classic WordPress way of doing things.
> - Build block themes and give users a “beta” experience in the Full Site Editor
>     - The Site Editor is still rough around the edges and for users who are familiar with the classic dashboard it can be confusing and frustrating. 
> 
> Neither of these options is ideal. Enter universal themes.
> 
> Universal themes are an attempt to use the benefits of both approaches.
