### ISSUE TITLE
No loop on the blog page (with static homepage)

### ISSUE THREAD

**Issue by alboth** [timber/starter-theme#38]
I have changed my blog settings > reading that the front page displays a static page. That works fine and i can also modify the template with a front-page.php. 

But - the post page named "News" also just shows the page content of the page "News", but not the latest posts. The body tags shows

`<body class="blog logged-in admin-bar  customize-support" data-template="base.twig">`

So obviously the theme already wants to display the "blog" here. For some reasons it doesn't work out. Also didn't find anything in the documentation about how to fix this issue.

But in general - thanks guy for this wonderful templating engine. WordPress starts to make sense again thanks to you.

**Comment by corygibbons** [comment]
I just tried it with a fresh install of WP and everything seems to be working as expected for me.

Have you customized `index.php` or `home.php` at all? Only thing I can think is you have a PHP file trying to load the wrong view.

**Comment by alboth** [comment]
Thank you for you fast answer. I pulled a fresh theme and -- it's working. You are unfortunately right. Sorry for bothering you with my mistakes.

**Comment by marciojc** [comment]
@jarednova we can close this issue as @alboth says that his problem was solved.
