### ISSUE TITLE
register_taxonomies before register_post_types

### ISSUE THREAD

**Issue by danburzo** [timber/starter-theme#43]
A small detail, but it's often the case that custom post types will supoort a custom taxonomy, so it's useful to have the call to `register_taxonomies` before `register_post_types`.

**Comment by danburzo** [comment]
Or is it the case that people normally use [`register_taxonomy_for_object_type()`](https://codex.wordpress.org/Function_Reference/register_taxonomy_for_object_type) inside `register_taxonomies`?

**Comment by jarednova** [comment]
@danburzo — can you submit a PR with current best practices? I'd love to get that up-to-date

**Comment by danburzo** [comment]
Sorry, seems the problem was in a different part of my code, and actually the registration order does not seem to matter 🤔
