### ISSUE TITLE
TimberSite doesn't exists.

### ISSUE THREAD

**Issue by kristijansoldo** [timber/starter-theme#54]
I can't extend TimberSite class.

https://github.com/timber/starter-theme/blob/c7e064d09aba3ff2ce27ce76682399bf58e3535f/functions.php#L17

**Comment by jarednova** [comment]
@kristijansoldo @Skadi2k3 I've confirmed that this is up-to-date in the current version on master:

https://github.com/timber/starter-theme/blob/master/functions.php
