### ISSUE TITLE
Getting search results to work

### ISSUE THREAD

**Issue by ama5** [timber/starter-theme#57]
I am experiencing a challenge getting search results in a theme created with Timber and using the Timber starter theme. I've documented my issue [here](https://stackoverflow.com/questions/48310429/timber-search-results-not-working). In doing some further troubleshooting, I created a new site with default WP content and loaded the Timber starter theme with no modifications. Regardless of the search term (including gibberish), the results page returns the 'Hello World!' post. Thanks!

**Comment by Levdbas** [comment]
I think this should be outdated by now. Closing
