### ISSUE TITLE
Wordpress SEO plugin (Yoast and SEO Framework) create a conflict with Timber plugin

### ISSUE THREAD

**Issue by filnug** [timber/starter-theme#58]
I'm using the Timber plugin with Underscores.me template (https://github.com/timber/starter-theme) to create a website (manual install).

I used the Yoast and SEO Framework plugin and both create an issue! When I add a description in the meta of a page, Timber doesn't work anymore. There is no error message. But content is empty.

I have:
WordPress 4.9.2
Timber Version 1.6.0
The SEO Framework Version 3.0.3

Do you have an idea why?

**Comment by filnug** [comment]
I tried to unactivate the other plugins, but the problem is still here. 
Am I the only one to have this problem?

**Comment by sybrew** [comment]
To view error messages, you need to activate debugging:
https://codex.wordpress.org/Debugging_in_WordPress#WP_DEBUG
