### ISSUE TITLE
Timber + AFC template resource bug

### ISSUE THREAD

**Issue by dzienisz** [timber/starter-theme#60]
Hi, I'm new to Wordpress Timber + AFC theme development.

I read all the `Getting started` pages and set up my local env.

I stopped when I wanted to use `Other resources` -> `This branch of the starter theme has some more example code with ACF and a slightly different set up.`

This link is broken. It led me to branch that is something better than template but without AFC features. Maybe it's this branch: https://github.com/laras126/timber-starter-theme/tree/options-demo?

Please fix that or delete completely.

I assume that I can't recreate that easily but I already spend like 2 hours to dig though this without any effect in code 👎

**Comment by Levdbas** [comment]
I could not find this reference anymore, closing
