### ISSUE TITLE
Would it be possible to dual license it?

### ISSUE THREAD

**Issue by dannycolin** [timber/starter-theme#65]
Hi,

Would it be possible to dual license the starter-theme under the MIT License and the GPLv2+ License?

Why i'm asking that : 

I'm working on a theme and I would like to release it under a GPLv2+ so that any derivative works would need to release their modifications under the same license. In other words, it would give us the choice to use a Copyleft license.

I know it is possible to license only my code under the GPL and keep yours under the MIT but I don't really like mixing licenses. It's not really convivial for people you want to reuse the code after that. 

I also want to use a GPL License to respect the choice made by the Wordpress team [[1][wp-license]].

> There is some legal grey area regarding what is considered a derivative work, but we feel strongly that plugins and themes are derivative work and thus inherit the GPL license.

Of course, you can disagree ;) but it would be nice to let the user of the starter-theme to make their own choice.

Thank you in advance for taking the time to read me.

[wp-license]: https://wordpress.org/about/license/

**Comment by dannycolin** [comment]
Don't want to rush anyone but is that repository still active?

**Comment by jarednova** [comment]
Hi @dannycolin — sorry, you caught me when I was away on paternity leave. While Timber itself might pose some issues, the starter theme is meant to be just as much as an example/template vs. a piece of software.

You're free to dual-license this repo or convert to GPL if that suits your purposes better

**Comment by dannycolin** [comment]
Thanks, it's really appreciate :).
