### ISSUE TITLE
Title Tag duplicated with Yoast SEO

### ISSUE THREAD

**Issue by pascalknecht** [timber/starter-theme#69]
Sometimes the title tag gets duplicated with the current setup when using Yoast SEO Plugin.

**Comment by alexwoollam** [comment]
This is a real stab in the dark without seeing any src/yeost settings, but:

Have you hard-coded the `<title>`?

Check this line in the functions.php (in the theme_supports function):

```
                 /*
		 * Let WordPress manage the document title.
		 * By adding theme support, we declare that this theme does not use a
		 * hard-coded <title> tag in the document head, and expect WordPress to
		 * provide it for us.
		 */
		add_theme_support( 'title-tag' );
```
