### ISSUE TITLE
NOTICE: wp-content/themes/starter-theme-master/sidebar.php:9 - Undefined variable: data

### ISSUE THREAD

**Issue by chrisjimallen** [timber/starter-theme#80]
I noticed that `$data` is not actually defined anywhere in the theme. Am I missing something or is this a bug?

ie. `sidebar.php`
```
Timber::render( array( 'sidebar.twig' ), $data );
```

**Comment by lkraav** [comment]
It's probably in scope within the function performing `include()` statement.

**Comment by jarednova** [comment]
@lkraav is correct
