### ISSUE TITLE
PHP Fatal Error - TWIG

### ISSUE THREAD

**Issue by yoursiteneedsme** [timber/starter-theme#89]
My site is giving off this error:

[Wed Sep 04 18:04:09.484966 2019] [php7:error] [pid 3862] [client 23.31.164.153:11890] PHP Fatal error: Uncaught RuntimeException: Passing a name as a first argument to the Twig\\Environment::addFilter method is deprecated since version 1.21. Pass an instance of "Twig_SimpleFilter" instead when defining filter "place_button". in /nas/content/live/benchmarkunive/wp-content/plugins/event-tickets/common/src/functions/utils.php:504\nStack trace:\n#0 [internal function]: tribe_catch_and_throw(16384, 'Passing a name ...', '/nas/content/li...', 1123, Array)\n#1 /nas/content/live/benchmarkunive/wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(1123): trigger_error('Passing a name ...', 16384)\n#2 /nas/content/live/benchmarkunive/wp-content/themes/backoffice/functions.php(82): Twig\\Environment->addFilter('place_button', Object(Twig\\TwigFilter))\n#3 [internal function]: StarterSite->add_to_twig(Object(Twig\\Environment))\n#4 /nas/content/live/benchmarkunive/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)\n#5 /nas/content/live/benchmarkunive/wp-includes/plugin.php(208): WP_Hook->apply_fi in /nas/content/live/benchmarkunive/wp-content/plugins/event-tickets/common/src/functions/utils.php on line 504, referer: https://www.benchmarkbackoffice.com/wp-admin/

**Comment by Levdbas** [comment]
Closing this as outdated
